name: catalyst
channels:
- defaults
- conda-forge
dependencies:
- ca-certificates=2017.08.26
- certifi=2018.1.18
- intel-openmp=2018.0.0
- mkl=2018.0.1
- numpy=1.14.0
- openssl=1.0.2n
- matplotlib=2.1.2=py36_0
- pip=9.0.1
- python=3.6.4
- scipy=1.0.0
- setuptools=38.4.0=py36_0
- sqlite=3.22.0
- tk=8.6.7
- wheel=0.30.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - aiodns==1.1.1
  - aiohttp==3.0.1
  - alembic==0.9.7
  - async-timeout==2.0.0
  - attrdict==2.0.0
  - attrs==17.4.0
  - bcolz==0.12.1
  - boto3==1.5.27
  - botocore==1.8.41
  - bottleneck==1.2.1
  - cchardet==2.1.1
  - ccxt==1.12.131
  - chardet==3.0.4
  - click==6.7
  - contextlib2==0.5.5
  - cyordereddict==1.0.0
  - cython==0.27.3
  - cytoolz==0.9.0
  - decorator==4.2.1
  - docutils==0.14
  - empyrical==0.2.1
  - enigma-catalyst>=0.5.3
  - eth-abi==1.0.0b0
  - eth-account==0.1.0a2
  - eth-keyfile==0.5.1
  - eth-keys==0.2.0b1
  - eth-rlp==0.1.0a2
  - eth-utils==1.0.0b1
  - hexbytes==0.1.0b0
  - idna==2.6
  - idna-ssl==1.0.0
  - intervaltree==2.1.0
  - jmespath==0.9.3
  - logbook==1.2.1
  - lru-dict==1.1.6
  - lxml==4.1.1
  - mako==1.0.7
  - markupsafe==1.0
  - multidict==4.1.0
  - multipledispatch==0.4.9
  - networkx==2.1
  - numexpr==2.6.4
  - pandas==0.19.2
  - pandas-datareader==0.6.0
  - patsy==0.5.0
  - pycares==2.3.0
  - pycryptodome==3.4.11
  - pysha3==1.0.2
  - python-dateutil==2.6.1
  - python-editor==1.0.3
  - pytz==2018.3
  - redo==1.6
  - requests==2.18.4
  - requests-file==1.4.3
  - requests-ftp==0.3.1
  - requests-toolbelt==0.8.0
  - rlp==0.6.0
  - s3transfer==0.1.12
  - six==1.11.0
  - sortedcontainers==1.5.9
  - sqlalchemy==1.2.2
  - statsmodels==0.8.0
  - tables==3.4.2
  - toolz==0.9.0
  - urllib3==1.22
  - web3==4.0.0b9
  - wrapt==1.10.11
  - yarl==1.1.0
